### ISSUE TITLE
Support lazy_dataset.new(other_dataset)

### ISSUE THREAD

**Issue by thequilo** [fgnt/lazy_dataset#46]
It would be logical if `lazy_dataset.new` would accept another dataset, like this:
```python
import lazy_dataset
lazy_dataset.new(lazy_dataset.new([1, 2, 3, 4]))
```
But it is unclear how `new` should handle datasets. It could
 - return the input dataset
 - make a copy of the dataset (`return dataset.copy(freeze=??)`)
 - cache and transform into `ListDataset` or `DictDataset`, i.e., `lazy_dataset.new(list(lazy_dataset.new([1, 2, 3, 4])))` or `lazy_dataset.new(dict(lazy_dataset.new({'a': 1, 'b': 2})))`

**Comment by boeddeker** [comment]
Do you know another library, that implements a `new` function?
If there is a common behavior, we should mirror that.

> cache and transform into ListDataset or DictDataset, i.e., lazy_dataset.new(list(lazy_dataset.new([1, 2, 3, 4]))) or lazy_dataset.new(dict(lazy_dataset.new({'a': 1, 'b': 2})))

I have a preference for this, because of the name `new`.

> make a copy of the dataset (return dataset.copy(freeze=??))

The copy feels strange, because in the case you want to manipulate something, you should be verbose and call copy.
It is very rare, that you need to call copy, because the Dataset tries to be immutable (You can always manipulate the attributes, but this is in general a bad idea for most Python objects).

> return the input dataset

For such a behavior, it would be more natural to call `lazy_dataset.Dataset(...)`.

**Comment by thequilo** [comment]
> Do you know another library, that implements a `new` function?

No, I don't know any other library.

> I have a preference for this, because of the name `new`.

I also prefer this behavior. Together with #47 this can restore keys after some operations like `filter`. I would wait until #47 is merged before implementing this.

I'll add another idea: What about allowing a `key_fn` parameter for `lazy_dataset.from_dataset` so that keys can be restored for some other operations like `batch`, for example like `lazy_dataset.from_dataset(ds.batch().map(collate_fn), key_fn=lambda x: '_'.join(x['example_id'])`? The same could be useful for `from_list`.

**Comment by boeddeker** [comment]
> I'll add another idea: What about allowing a key_fn parameter for lazy_dataset.from_dataset so that keys can be restored for some other operations like batch, for example like lazy_dataset.from_dataset(ds.batch().map(collate_fn), key_fn=lambda x: '_'.join(x['example_id'])? The same could be useful for from_list.

A function that adds keys based on the values, requires lazy keys. That is difficult, because you cannot use it, without expensive computations.

**Comment by thequilo** [comment]
It would work in this place, though, because the `new` function always iterates over the whole dataset before creating the new one. So, we have all data and the keys wouldn't have to be lazy.

**Comment by boeddeker** [comment]
I wasn't carefully reading your example, if you want to have the described problem solved, you can simply write:
```python
lazy_dataset.new(dict([
    ('_'.join(x['example_id']), x) for x in ds.batch().map(collate_fn)
]))
```
or
```python
lazy_dataset.new(dict(ds.batch().map(collate_fn).map(lambda x: ('_'.join(x['example_id']), x))))
```
Here, I prefer to use basic python. Using the solution with map it is similar to `key_fn`.

To simplify the creation from items, we could add a `from_items` function:
```python
def from_items(items):
     return from_dict(dict(items))
```
or similar to `dict(...)` allow a dicts and items at the input of `from_dict`.
